# Configuración por defecto, se aplica a todos los entornos
default:
  server.port: 9001
  hibernate.connection.url: "jdbc:postgresql://localhost:5432/prueba"
  hibernate.connection.username: "postgres"
  hibernate.connection.password: "clave_supersegura"
  GCP_PROJECT_ID: "metamapa-477204"

# Entorno de Desarrollo (se activa si no se especifica otro)
dev:
  almacenamiento.archivos: "local"
  media.url: "http://localhost:9001"

# Entorno de Producción (se activa con -Dapp.env=prod)
prod:
  hibernate.connection.url: "jdbc:postgresql://dpg-d4g7sos9c44c73d7ms60-a.oregon-postgres.render.com:5432/clouddb_rc1c?sslmode=require"
  hibernate.connection.username: "clouddb_rc1c_user"
  hibernate.connection.password: "wdXgw1VTi8FSVxZCiXnZ9q61wrns9mDe"
  almacenamiento.archivos: "cloudfare"