# Configuración por defecto, se aplica a todos los entornos
default:
  server.port: 9001
  hibernate.connection.url: "jdbc:postgresql://localhost:5432/prueba"
  hibernate.connection.username: "postgres"
  hibernate.connection.password: "clave_supersegura"
  GCP_PROJECT_ID: "metamapa-477204"

# Entorno de Desarrollo (se activa si no se especifica otro)
dev:
  almacenamiento.archivos: "local"
  media.url: "http://localhost:9001"

# Entorno de Producción (se activa con -Dapp.env=prod)
prod:
  hibernate.connection.url: "jdbc:postgresql://10.142.0.3:5432/metamapa"
  almacenamiento.archivos: "cloudfare"
  media.url: "https://media.metamapa.com.ar"